# Generated by Django 5.0.6 on 2024-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("created_At", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Users",
                "db_table": "Users",
                "ordering": ("-created_At",),
            },
        ),
    ]
